INSERT INTO police_report (name, report, map, severe_score) VALUES
('Domingos Holden', 'VYyPJw', 'Lockinge', 2),
('Isabel Enid', NULL, 'Findochty', 7),
('Tadgán Musa', 'FgDqud', 'Kara''s Vale', 10),
('Filip Baxter', 'D1rJqH', 'Kirekwall', 3),
('Edorta Elias', 'pQ53RC', 'Dewsbury', 9),
('K?mal Davy', 'BsI86j', 'Kara''s Vale', 2),
('Isokrates Bituin', NULL, 'Findochty', 5),
('Kassy Ramirus', 'Pkjv7J', 'Kirekwall', 7),
('Doris Blessing', '0kJXq1', 'Dalmerlington', 6),
('Nedeljka Ganesh', 'EVe9ha', 'Kara''s Vale', 8),
('Karlene Timotheus', '2HUBHz', 'Dewsbury', 7),
('Emerens Raman', 'PAGdHl', 'Findochty', 1),
('Mijo Ambrosios', NULL, 'Luton', 5),
('Karlene Jairus', '4Z63Q5', 'Dalmerlington', 8),
('Khordad Peter', NULL, 'Findochty', 2),
('Biagio Mai', NULL, 'Findochty', 9),
('Liwen Sigiward', 'B51ETs', 'Mansfield', 3),
('Svante Mona', 'DC0kGh', 'Caerleon', 5),
('Kshitija Ladislav', 'cSA0hA', 'Caerleon', 2),
('Ha-Eun Tatiana', 'YNYhHV', 'Kara''s Vale', 4);